### ISSUE TITLE
Only says player connected "Amarok" (I don't have amarok installed, but spotify and itunes are running)

### ISSUE THREAD

**Issue by inspire22** [sunny/anyplayer#9]
~ ➤ gem install anyplayer
Fetching: ruby-mpd-0.3.2.gem (100%)
Successfully installed ruby-mpd-0.3.2
Fetching: anyplayer-1.1.4.gem (100%)
Successfully installed anyplayer-1.1.4
2 gems installed
~ ➤ anyplayer
sh: line 1: 23309 Trace/BPT trap: 5       qdbus org.kde.amarok 2>&1
Usage: anyplayer [-v] [command]

Where command is one of: playpause, play, pause, next, prev, voldown, volup, volume, track, artist, album, vote, name, launched, paused, playing.

Player connected: Amarok.
~ ➤ anyplayer
sh: line 1: 23323 Trace/BPT trap: 5       qdbus org.kde.amarok 2>&1
Usage: anyplayer [-v] [command]

Where command is one of: playpause, play, pause, next, prev, voldown, volup, volume, track, artist, album, vote, name, launched, paused, playing.

Player connected: Amarok.
~ ➤ anyplayer pause
sh: line 1: 23330 Trace/BPT trap: 5       qdbus org.kde.amarok 2>&1
dyld: Library not loaded: QtCore.framework/Versions/4/QtCore
  Referenced from: /usr/bin/qdbus
  Reason: image not found

~ ➤ anyplayer launched
sh: line 1: 23381 Trace/BPT trap: 5       qdbus org.kde.amarok 2>&1
sh: line 1: 23384 Trace/BPT trap: 5       qdbus org.kde.amarok 2>&1
~ ➤ ruby -v
ruby 2.0.0p195 (2013-05-14 revision 40734) [x86_64-darwin12.2.0]
~ ➤

Do I need to install a different version of Qt or something?  Seems strange...

**Comment by sunny** [comment]
Thanks for reporting this! Can you try the following commands?

```sh
$ which qdbus
$ qdbus org.kde.amarok
```

**Comment by inspire22** [comment]
Thanks :)  I'm still on 10.9.5, perhaps that is related.

pro ➤  which qdbus
/usr/bin/qdbus
pro ➤ qdbus org.kde.amarok
dyld: Library not loaded: QtCore.framework/Versions/4/QtCore
  Referenced from: /usr/bin/qdbus
  Reason: image not found
[1]    25841 trace trap  qdbus org.kde.amarok

**Comment by sunny** [comment]
Hmm. Looks like you have `qdbus` which is unusual under OSX. I have added another layer of platform-detection in #10 so that Amarok doesn't even get tested under OSX.

Can you try it out? If this works I'll release a new version with the fix.

To try it out:

```
git clone -b players-can-specify-platform https://github.com/sunny/anyplayer.git
cd anyplayer
bundle
ruby -Ilib bin/anyplayer -v artist
```

**Comment by sunny** [comment]
Hey @inspire22, have you had the chance to see if this fixes your issue?

**Comment by inspire22** [comment]
Thanks!  Yes, it correctly shows the artist of the paying song in itunes/mac now :)

I'd been hoping to hack my amazon echo to play music on my stereo with this via the todo-list feature on it, but it doesn't seem possible to change the running track on itunes with this unfortunately.  Though I do see the applescript it uses so could try and hack something up myself..

**Comment by sunny** [comment]
Thank you Kevin! Glad this fix works for you.

If you manage to find a solution for your amazon echo I'd be curious to
know how you did it and to know if we could add it to anyplayer.

Thanks again for reporting this!
